### ISSUE TITLE
Remove version inconsistency between spec document and other parts of the component spec

### ISSUE THREAD

**Issue by JanWesterkamp-iJUG** [eclipse/microprofile-telemetry#84]
**Describe the bug**

OTel artifacts using semver for versioning, with some declared exeptions regarding experimental, alpha versions and currently regarding some telemetry data.
The spec document cuts the PATCH part of the referenced OTel versions - this leads to potential deviations from the spec document to the API and TCK, when there are multiple PATCH versions of the OTel artifacts available.
This can result in using a broken or insecure version!

References to OTel dependencies (and all other too - but that a different discussion) must show and use the exact version (as a minimum version to use).
With semver in place, it is possible to use a higher version (i.e. in the implementation), when allowed in respect to the semver rules - may be we should clarify this in the spec document in a future release.

A last minute change of the MP Telemetry 1.0 introduced this change - we must revert this:
https://github.com/eclipse/microprofile-telemetry/pull/70

If the intention of this change was to handle recent OTel PATCH version releases we should define separate versions for the opentelemetry-spec, opentelemetry-java and opentelemetry-java-instrumentation, so PATCH release deviation can be handled and shown in the spec document.

@Emily-Jiang, @brunobat and @Azquelt: I can create a PR to solve this if you agree or we can discuss this on our next meeting, as you like to do.

**Comment by Azquelt** [comment]
I think you're suggesting two changes:

- Change OTel versions in the spec to include the patch version
- Change all references to required versions of OTel to say "this version or later"

Is that right?

**Comment by Azquelt** [comment]
We did talk about this in the meeting.

My concerns were:

1. We do want to allow implementations to pick up new patch versions which #70 did, so we don't want to entirely revert that PR
2. We can't say something like "1.19.0 or any later minor version" because we rely on some components which are still experimental (particularly semconv and autoconfigure) so even minor versions of those components may have breaking changes.

However, I am happy if we want to change how things are worded in the spec to something like "1.19.0 or any later patch version" - which would allow us to only have one version defined in the pom and allows us to specify a minimum patch version (e.g. if there was a security fix and we wanted to require 1.19.1).

We could go as far as saying "1.19.0 or any later version without breaking changes" which would then put the onus on implementers to check whether 1.20.0 actually has any breaking changes in its experimental components, but that wouldn't be an easy thing to assert.

With more of OTel becoming stable, it's also possible that in a future version of MP Telemetry we might be able to only depend on stable parts and then it might be possible to say "1.19.0 or any later minor version", but we're not there yet.

Lastly, we briefly mentioned using the TCK to assert compatibility. While I would like to improve and expand the TCK to cover more of the areas that the spec requires (e.g. more complete testing of the config options specified by autoconfigure), we will never be able to say "if you can update the version of OTel and still pass the TCK, it doesn't have any breaking changes". Breaking changes can be small and subtle and TCK coverage will never be that complete.

More generally, the TCK for any spec will only ever test a subset, passing the TCK doesn't mean you've accurately implemented the spec (though failing it should always indicate that you haven't).

**Comment by Emily-Jiang** [comment]
I am with @Azquelt on this. I don't think we need to do a spec update to pull in a micro version release of OpenTelemetry. This prevents implementations from consuming the latest CVE fixes without a spec update. By the way, the micro version release of OpenTelemetry should not bring in any functional changes except very minor internal fixes.

**Comment by Emily-Jiang** [comment]
We think the version are consistent now. Please reopen if you think otherwise.
